# https://github.com/marketplace/actions/delete-workflow-runs
name: Delete old workflow runs
on:
  schedule:
    - cron: "0 4 * * 1" # Weekly on Monday at 04:00
  # to allow manual triggering of the workflow from the GitHub Actions tab:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:

      - name: Delete all successful dependabot and cleanup runs
        # releaseNuget runs are not deleted, they are the record of what was published to nuget.org
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: dependabot|cleanup
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: success


      - name: Delete all but the last successful run of build, docs and checkLinks
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: build|docs|checkLinks
          retain_days: 0
          # keep only the last build, docs and checkLinks run for the badges in the readme,
          # this job runs one per action name.
          # this will also keep runs older than 'retain_days'
          keep_minimum_runs: 1
          delete_run_by_conclusion_pattern: success

      - name: Delete all failed runs older than 30 days
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled, failure, skipped
